GET http://localhost:5070/books

###

GET http://localhost:5070/books/1

###

POST http://localhost:5070/books
Content-Type: application/json

{
    "name": "Wiedźmin - ostatni rycerz",
    "genreId": 2,
    "price": 20.99,
    "authorId": 3,
    "releaseDate": "2011-10-21"
}

###

PUT http://localhost:5070/books/3
Content-Type: application/json

{
    "name": "Harry Potter 2",
    "genreId": 2,
    "price": 25.51,
    "authorId": 1,
    "releaseDate": "2020-09-12"
}

###

DELETE http://localhost:5070/books/1