GET http://localhost:5070/books

###

GET http://localhost:5070/books/4

###

POST http://localhost:5070/books
Content-Type: application/json

{
    "name": "Tokyo ghoul",
    "genre": "Manga",
    "price": "20.99",
    "author": "Sui Ishida",
    "releaseDate": "2011-10-21"
}

###

PUT http://localhost:5070/books/1
Content-Type: application/json

{
    "name": "Harry Potter 2",
    "genre": "Fantasy",
    "price": 25.51,
    "author": "J.K Rolling",
    "releaseDate": "2020-09-12"
}

###

DELETE http://localhost:5070/books/1